#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 1
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_identifier = 1,
  anon_sym_DOT = 2,
  anon_sym_send = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  aux_sym_port_token1 = 6,
  sym_host = 7,
  anon_sym_msg = 8,
  anon_sym_AMP_AMP = 9,
  anon_sym_PIPE_PIPE = 10,
  anon_sym_STAR = 11,
  anon_sym_SLASH = 12,
  anon_sym_PERCENT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_LT_LT = 16,
  anon_sym_GT_GT = 17,
  anon_sym_AMP = 18,
  anon_sym_CARET = 19,
  anon_sym_PIPE = 20,
  anon_sym_LT = 21,
  anon_sym_LT_EQ = 22,
  anon_sym_EQ_EQ = 23,
  anon_sym_BANG_EQ = 24,
  anon_sym_GT_EQ = 25,
  anon_sym_GT = 26,
  anon_sym_TILDE = 27,
  anon_sym_BANG = 28,
  aux_sym_number_token1 = 29,
  anon_sym_e = 30,
  anon_sym_E = 31,
  aux_sym_dollar_variable_token1 = 32,
  aux_sym_dollar_variable_token2 = 33,
  aux_sym_dollar_variable_token3 = 34,
  aux_sym_dollar_variable_token4 = 35,
  anon_sym_LBRACK = 36,
  aux_sym_dollar_variable_token5 = 37,
  anon_sym_RBRACK = 38,
  aux_sym_subpatch_variable_token1 = 39,
  aux_sym_subpatch_variable_token2 = 40,
  aux_sym_subpatch_variable_token3 = 41,
  anon_sym_SLASH_SLASH = 42,
  aux_sym_comment_token1 = 43,
  sym__delimiter = 44,
  sym_program = 45,
  sym_send_statement = 46,
  sym_send_block = 47,
  sym_port = 48,
  sym_message_block = 49,
  sym_expression = 50,
  sym_parenthesized = 51,
  sym_boolean_operator = 52,
  sym_binary_operator = 53,
  sym_comparison_operator = 54,
  sym_unary_operator = 55,
  sym_number = 56,
  sym_function = 57,
  sym_arguments = 58,
  sym_dollar_variable = 59,
  sym_subpatch_variable = 60,
  sym_comment = 61,
  aux_sym_program_repeat1 = 62,
  aux_sym_send_statement_repeat1 = 63,
  aux_sym_message_block_repeat1 = 64,
  aux_sym_arguments_repeat1 = 65,
  alias_sym_name = 66,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOT] = ".",
  [anon_sym_send] = "keyword_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_port_token1] = "port_token1",
  [sym_host] = "host",
  [anon_sym_msg] = "keyword_identifier",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_AMP] = "&",
  [anon_sym_CARET] = "^",
  [anon_sym_PIPE] = "|",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_TILDE] = "~",
  [anon_sym_BANG] = "!",
  [aux_sym_number_token1] = "number_token1",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [aux_sym_dollar_variable_token1] = "identifier",
  [aux_sym_dollar_variable_token2] = "identifier",
  [aux_sym_dollar_variable_token3] = "identifier",
  [aux_sym_dollar_variable_token4] = "identifier",
  [anon_sym_LBRACK] = "list_pattern",
  [aux_sym_dollar_variable_token5] = "list_pattern",
  [anon_sym_RBRACK] = "list_pattern",
  [aux_sym_subpatch_variable_token1] = "identifier",
  [aux_sym_subpatch_variable_token2] = "identifier",
  [aux_sym_subpatch_variable_token3] = "identifier",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__delimiter] = "_delimiter",
  [sym_program] = "program",
  [sym_send_statement] = "send_statement",
  [sym_send_block] = "send_block",
  [sym_port] = "port",
  [sym_message_block] = "message_block",
  [sym_expression] = "expression",
  [sym_parenthesized] = "parenthesized",
  [sym_boolean_operator] = "boolean_operator",
  [sym_binary_operator] = "binary_operator",
  [sym_comparison_operator] = "comparison_operator",
  [sym_unary_operator] = "unary_operator",
  [sym_number] = "number",
  [sym_function] = "function",
  [sym_arguments] = "arguments",
  [sym_dollar_variable] = "dollar_variable",
  [sym_subpatch_variable] = "subpatch_variable",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_send_statement_repeat1] = "send_statement_repeat1",
  [aux_sym_message_block_repeat1] = "message_block_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [alias_sym_name] = "name",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_send] = anon_sym_send,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_port_token1] = aux_sym_port_token1,
  [sym_host] = sym_host,
  [anon_sym_msg] = anon_sym_send,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [aux_sym_dollar_variable_token1] = sym_identifier,
  [aux_sym_dollar_variable_token2] = sym_identifier,
  [aux_sym_dollar_variable_token3] = sym_identifier,
  [aux_sym_dollar_variable_token4] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_dollar_variable_token5] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_LBRACK,
  [aux_sym_subpatch_variable_token1] = sym_identifier,
  [aux_sym_subpatch_variable_token2] = sym_identifier,
  [aux_sym_subpatch_variable_token3] = sym_identifier,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__delimiter] = sym__delimiter,
  [sym_program] = sym_program,
  [sym_send_statement] = sym_send_statement,
  [sym_send_block] = sym_send_block,
  [sym_port] = sym_port,
  [sym_message_block] = sym_message_block,
  [sym_expression] = sym_expression,
  [sym_parenthesized] = sym_parenthesized,
  [sym_boolean_operator] = sym_boolean_operator,
  [sym_binary_operator] = sym_binary_operator,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_unary_operator] = sym_unary_operator,
  [sym_number] = sym_number,
  [sym_function] = sym_function,
  [sym_arguments] = sym_arguments,
  [sym_dollar_variable] = sym_dollar_variable,
  [sym_subpatch_variable] = sym_subpatch_variable,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_send_statement_repeat1] = aux_sym_send_statement_repeat1,
  [aux_sym_message_block_repeat1] = aux_sym_message_block_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [alias_sym_name] = alias_sym_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_send] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_port_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_host] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_msg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dollar_variable_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dollar_variable_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dollar_variable_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dollar_variable_token4] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dollar_variable_token5] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_subpatch_variable_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_subpatch_variable_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_subpatch_variable_token3] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__delimiter] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_send_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_send_block] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_message_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_dollar_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_subpatch_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_send_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_name] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[2][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_name,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '!') ADVANCE(41);
      if (lookahead == '$') ADVANCE(57);
      if (lookahead == '%') ADVANCE(25);
      if (lookahead == '&') ADVANCE(30);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(64);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '0') ADVANCE(18);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '^') ADVANCE(31);
      if (lookahead == 'p') ADVANCE(58);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '~') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '$') ADVANCE(57);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(18);
      if (lookahead == 'p') ADVANCE(58);
      if (lookahead == '~') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(57);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(52);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(53);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(55);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '%') ADVANCE(25);
      if (lookahead == '&') ADVANCE(30);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(64);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '^') ADVANCE(31);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_port_token1);
      if (lookahead == '.') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_port_token1);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_port_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_host);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(21);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(22);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead == '0' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_dollar_variable_token5);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_subpatch_variable_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_subpatch_variable_token1);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_subpatch_variable_token2);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_subpatch_variable_token3);
      if (('!' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(46);
      if (lookahead == 'y') ADVANCE(47);
      if (lookahead == 'f' ||
          lookahead == 'i' ||
          lookahead == 's' ||
          lookahead == 'v') ADVANCE(59);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '0' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__delimiter);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'E') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'm') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 3:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'g') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_msg);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_send);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 11},
  [62] = {.lex_state = 11},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 11},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 11},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 11},
  [80] = {.lex_state = 11},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 11},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 11},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 62},
  [89] = {(TSStateId)(-1)},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_send] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_port_token1] = ACTIONS(1),
    [anon_sym_msg] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [aux_sym_dollar_variable_token1] = ACTIONS(1),
    [aux_sym_dollar_variable_token2] = ACTIONS(1),
    [aux_sym_dollar_variable_token3] = ACTIONS(1),
    [aux_sym_dollar_variable_token4] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_dollar_variable_token5] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_subpatch_variable_token1] = ACTIONS(1),
    [aux_sym_subpatch_variable_token2] = ACTIONS(1),
    [aux_sym_subpatch_variable_token3] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__delimiter] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(86),
    [sym_send_statement] = STATE(71),
    [sym_send_block] = STATE(85),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(57),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_send] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    STATE(2), 1,
      sym_comment,
    STATE(76), 1,
      sym_expression,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(35), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [53] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    STATE(3), 1,
      sym_comment,
    STATE(68), 1,
      sym_expression,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(35), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [106] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(4), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(37), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [156] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(55), 1,
      sym__delimiter,
    STATE(5), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    STATE(63), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [218] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(6), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(34), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [268] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(59), 1,
      sym_identifier,
    STATE(7), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(42), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [318] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(8), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(43), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [368] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(63), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(33), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [418] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(44), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [468] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(11), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(45), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [518] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(12), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(46), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [568] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(71), 1,
      sym_identifier,
    STATE(13), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(47), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [618] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(73), 1,
      sym_identifier,
    STATE(14), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(32), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [668] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(75), 1,
      sym_identifier,
    STATE(15), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(49), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [718] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(23), 1,
      aux_sym_subpatch_variable_token1,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(16), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym_subpatch_variable_token2,
      aux_sym_subpatch_variable_token3,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(54), 9,
      sym_parenthesized,
      sym_boolean_operator,
      sym_binary_operator,
      sym_comparison_operator,
      sym_unary_operator,
      sym_number,
      sym_function,
      sym_dollar_variable,
      sym_subpatch_variable,
  [768] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(81), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(79), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [803] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(18), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_RPAREN,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [860] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(89), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 9,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [905] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(20), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
  [958] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 5,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      sym__delimiter,
  [1009] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 5,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      sym__delimiter,
  [1058] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(23), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(93), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 11,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1101] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(24), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(93), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 13,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1142] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(93), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1179] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(26), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 3,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1234] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(27), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(95), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
  [1287] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(28), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 2,
      anon_sym_RPAREN,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1344] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(101), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1381] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_comment,
    STATE(50), 1,
      sym_arguments,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1437] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_comment,
    ACTIONS(107), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1471] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(55), 1,
      sym__delimiter,
    STATE(32), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1527] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 5,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      sym__delimiter,
  [1570] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(89), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 9,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1609] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(35), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 2,
      anon_sym_RPAREN,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1660] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(113), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(111), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1691] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_RPAREN,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [1742] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(117), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1773] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(121), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1804] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(125), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1835] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(101), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1866] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
  [1913] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 5,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_CARET,
      sym__delimiter,
  [1958] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(44), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(93), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 11,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [1995] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(45), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(93), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 13,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2030] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(93), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2061] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(47), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 3,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [2110] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(107), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2141] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    STATE(49), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
    ACTIONS(95), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      sym__delimiter,
  [2188] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(129), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2219] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(133), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2250] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(137), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2281] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(141), 5,
      anon_sym_SLASH,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(139), 15,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_CARET,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      sym__delimiter,
  [2312] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(41), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(43), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
  [2362] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_port_token1,
    ACTIONS(17), 1,
      aux_sym_number_token1,
    ACTIONS(21), 1,
      aux_sym_dollar_variable_token4,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(55), 1,
      sym_comment,
    ACTIONS(19), 3,
      aux_sym_dollar_variable_token1,
      aux_sym_dollar_variable_token2,
      aux_sym_dollar_variable_token3,
    STATE(41), 4,
      sym_parenthesized,
      sym_number,
      sym_function,
      sym_dollar_variable,
  [2395] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 1,
      anon_sym_send,
    STATE(71), 1,
      sym_send_statement,
    STATE(85), 1,
      sym_send_block,
    STATE(56), 2,
      sym_comment,
      aux_sym_program_repeat1,
  [2415] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      anon_sym_send,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      aux_sym_program_repeat1,
    STATE(57), 1,
      sym_comment,
    STATE(71), 1,
      sym_send_statement,
    STATE(85), 1,
      sym_send_block,
  [2437] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(154), 1,
      anon_sym_DOT,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_send,
    STATE(58), 2,
      sym_comment,
      aux_sym_send_statement_repeat1,
  [2452] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(159), 1,
      anon_sym_DOT,
    STATE(58), 1,
      aux_sym_send_statement_repeat1,
    STATE(59), 1,
      sym_comment,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_send,
  [2469] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(159), 1,
      anon_sym_DOT,
    STATE(59), 1,
      aux_sym_send_statement_repeat1,
    STATE(60), 1,
      sym_comment,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_send,
  [2486] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_send,
  [2498] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_send,
  [2510] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(55), 1,
      sym__delimiter,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym_arguments_repeat1,
  [2526] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 1,
      sym__delimiter,
    STATE(64), 2,
      sym_comment,
      aux_sym_arguments_repeat1,
  [2540] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(170), 1,
      aux_sym_port_token1,
    STATE(65), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2554] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    ACTIONS(176), 1,
      sym__delimiter,
    STATE(66), 2,
      sym_comment,
      aux_sym_message_block_repeat1,
  [2568] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    ACTIONS(181), 1,
      sym__delimiter,
    STATE(66), 1,
      aux_sym_message_block_repeat1,
    STATE(67), 1,
      sym_comment,
  [2584] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      sym__delimiter,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_message_block_repeat1,
    STATE(68), 1,
      sym_comment,
  [2600] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_send,
  [2612] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      sym__delimiter,
    STATE(70), 1,
      sym_comment,
  [2625] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      anon_sym_send,
  [2636] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      aux_sym_port_token1,
    STATE(70), 1,
      sym_port,
    STATE(72), 1,
      sym_comment,
  [2649] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(195), 1,
      anon_sym_msg,
    STATE(60), 1,
      sym_message_block,
    STATE(73), 1,
      sym_comment,
  [2662] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(195), 1,
      anon_sym_msg,
    STATE(61), 1,
      sym_message_block,
    STATE(74), 1,
      sym_comment,
  [2675] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(75), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_RPAREN,
      sym__delimiter,
  [2686] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(76), 1,
      sym_comment,
    ACTIONS(174), 2,
      anon_sym_RPAREN,
      sym__delimiter,
  [2697] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(199), 1,
      sym_host,
    STATE(77), 1,
      sym_comment,
  [2707] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(201), 1,
      aux_sym_dollar_variable_token5,
    STATE(78), 1,
      sym_comment,
  [2717] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(203), 1,
      anon_sym_DOT,
    STATE(79), 1,
      sym_comment,
  [2727] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(205), 1,
      aux_sym_port_token1,
    STATE(80), 1,
      sym_comment,
  [2737] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_comment,
  [2747] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(209), 1,
      anon_sym_DOT,
    STATE(82), 1,
      sym_comment,
  [2757] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_comment,
  [2767] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_comment,
  [2777] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(215), 1,
      anon_sym_DOT,
    STATE(85), 1,
      sym_comment,
  [2787] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
    STATE(86), 1,
      sym_comment,
  [2797] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      sym_comment,
  [2807] = 1,
    ACTIONS(221), 1,
      aux_sym_comment_token1,
  [2811] = 1,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 106,
  [SMALL_STATE(5)] = 156,
  [SMALL_STATE(6)] = 218,
  [SMALL_STATE(7)] = 268,
  [SMALL_STATE(8)] = 318,
  [SMALL_STATE(9)] = 368,
  [SMALL_STATE(10)] = 418,
  [SMALL_STATE(11)] = 468,
  [SMALL_STATE(12)] = 518,
  [SMALL_STATE(13)] = 568,
  [SMALL_STATE(14)] = 618,
  [SMALL_STATE(15)] = 668,
  [SMALL_STATE(16)] = 718,
  [SMALL_STATE(17)] = 768,
  [SMALL_STATE(18)] = 803,
  [SMALL_STATE(19)] = 860,
  [SMALL_STATE(20)] = 905,
  [SMALL_STATE(21)] = 958,
  [SMALL_STATE(22)] = 1009,
  [SMALL_STATE(23)] = 1058,
  [SMALL_STATE(24)] = 1101,
  [SMALL_STATE(25)] = 1142,
  [SMALL_STATE(26)] = 1179,
  [SMALL_STATE(27)] = 1234,
  [SMALL_STATE(28)] = 1287,
  [SMALL_STATE(29)] = 1344,
  [SMALL_STATE(30)] = 1381,
  [SMALL_STATE(31)] = 1437,
  [SMALL_STATE(32)] = 1471,
  [SMALL_STATE(33)] = 1527,
  [SMALL_STATE(34)] = 1570,
  [SMALL_STATE(35)] = 1609,
  [SMALL_STATE(36)] = 1660,
  [SMALL_STATE(37)] = 1691,
  [SMALL_STATE(38)] = 1742,
  [SMALL_STATE(39)] = 1773,
  [SMALL_STATE(40)] = 1804,
  [SMALL_STATE(41)] = 1835,
  [SMALL_STATE(42)] = 1866,
  [SMALL_STATE(43)] = 1913,
  [SMALL_STATE(44)] = 1958,
  [SMALL_STATE(45)] = 1995,
  [SMALL_STATE(46)] = 2030,
  [SMALL_STATE(47)] = 2061,
  [SMALL_STATE(48)] = 2110,
  [SMALL_STATE(49)] = 2141,
  [SMALL_STATE(50)] = 2188,
  [SMALL_STATE(51)] = 2219,
  [SMALL_STATE(52)] = 2250,
  [SMALL_STATE(53)] = 2281,
  [SMALL_STATE(54)] = 2312,
  [SMALL_STATE(55)] = 2362,
  [SMALL_STATE(56)] = 2395,
  [SMALL_STATE(57)] = 2415,
  [SMALL_STATE(58)] = 2437,
  [SMALL_STATE(59)] = 2452,
  [SMALL_STATE(60)] = 2469,
  [SMALL_STATE(61)] = 2486,
  [SMALL_STATE(62)] = 2498,
  [SMALL_STATE(63)] = 2510,
  [SMALL_STATE(64)] = 2526,
  [SMALL_STATE(65)] = 2540,
  [SMALL_STATE(66)] = 2554,
  [SMALL_STATE(67)] = 2568,
  [SMALL_STATE(68)] = 2584,
  [SMALL_STATE(69)] = 2600,
  [SMALL_STATE(70)] = 2612,
  [SMALL_STATE(71)] = 2625,
  [SMALL_STATE(72)] = 2636,
  [SMALL_STATE(73)] = 2649,
  [SMALL_STATE(74)] = 2662,
  [SMALL_STATE(75)] = 2675,
  [SMALL_STATE(76)] = 2686,
  [SMALL_STATE(77)] = 2697,
  [SMALL_STATE(78)] = 2707,
  [SMALL_STATE(79)] = 2717,
  [SMALL_STATE(80)] = 2727,
  [SMALL_STATE(81)] = 2737,
  [SMALL_STATE(82)] = 2747,
  [SMALL_STATE(83)] = 2757,
  [SMALL_STATE(84)] = 2767,
  [SMALL_STATE(85)] = 2777,
  [SMALL_STATE(86)] = 2787,
  [SMALL_STATE(87)] = 2797,
  [SMALL_STATE(88)] = 2807,
  [SMALL_STATE(89)] = 2811,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_operator, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_operator, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dollar_variable, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dollar_variable, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dollar_variable, 4),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dollar_variable, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 4),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 4),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 2, .production_id = 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 2, .production_id = 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subpatch_variable, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subpatch_variable, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(83),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_send_statement_repeat1, 2),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_send_statement_repeat1, 2), SHIFT_REPEAT(74),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_send_statement, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_send_statement, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_block, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(4),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_block_repeat1, 2),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_block_repeat1, 2), SHIFT_REPEAT(2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_block, 5),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_send_block, 4),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_send_block, 6),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [217] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_pdmsg(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
